### PR TITLE
fix: binding naming, imports and docs

### LINKED ISSUE #517: [fix] New Pybind wrapper uses incorrect naming
**Describe the bug**

The latest OSTK version appears to break naming standards in a way that requires us to put in some patches to get it to work.

1. In bindings/python/src/OpenSpaceToolkitAstrodynamicsPy.cxx, OpenSpaceAstrodynamicsPy_Estimator should be OpenSpaceToolkitAstrodynamicsPy_Estimator and OpenSpaceAstrodynamicsPy_Data should be OpenSpaceToolkitAstrodynamicsPy_Data. Similar changes need to be made in the related files.
2. bindings/python/tools/python/ostk/astrodynamics/utilities.py has the line 'from .OpenSpaceToolkitAstrodynamicsPy import *' which should be 'from ostk.astrodynamics import *', as the .OpenSpaceToolkitAstrodynamicsPy name should only be used in __init__.py, to match style of the rest of the python bindings.

**Expected behavior**
Style should match across the bindings, allowing our slight fork to continue to compile correctly.

### PR DESCRIPTION
**Pull request by vishwa2710**
Closes #517 

## Summary by CodeRabbit

- **Refactor**
  - Standardized the naming conventions in the Python API for greater consistency.
  
- **New Features**
  - Introduced functions to compute trajectory geometry and ground track.

- **Chore**
  - Enhanced the clarity of default parameters in the Python interface.
  - Updated dependency constraints in the Jupyter environment for improved reliability.

- **Documentation**
  - Expanded the API reference to include additional modules for easy discovery.

### CODE REVIEW

**Review by lucas-bremond — APPROVED** [review]

File: bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Estimator/TLESolver.cpp [hunk 1]
```diff
@@ -86,12 +86,12 @@ inline void OpenSpaceToolkitAstrodynamicsPy_Estimator_TLESolver(pybind11::module
                 const Integer&,
                 const bool,
                 const Shared<const Frame>&>(),
-            arg("solver") = LeastSquaresSolver::Default(),
+            arg_v("solver", LeastSquaresSolver::Default(), "LeastSquaresSolver.default()"),
             arg("satellite_number") = 0,
             arg("international_designator") = "00001A",
             arg("revolution_number") = 0,
             arg("estimate_b_star") = true,
```
Comment (apaletta3) [inline bindings/python/src/OpenSpaceToolkitAstrodynamicsPy/Estimator/TLESolver.cpp:93]: I think all of these should be arg_v
